[project]
name = "davidkhala.gcp"
version = "0.4.1"
description = "Core gcp components"
authors = [{ name = "David Liu", email = "david-khala@hotmail.com" }]
requires-python = "~=3.10"
readme = "README.md"
dependencies = [
    "google-auth[requests]",
    "google-api-core",
]

[project.optional-dependencies]
core = ["google-cloud-core"]

[dependency-groups]
dev = [
    "pytest",
    "google-cloud-language",
]

[tool.hatch.build.targets.sdist]
include = ["davidkhala"]

[tool.hatch.build.targets.wheel]
include = ["davidkhala"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
