name: Workload Identity Federation
on: push
jobs:
  setup:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'cloud-region@freetier-only.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/207043494928/locations/global/workloadIdentityPools/github/providers/github-action'